export const cardlist = [
    {
      name: "krishna Venkatesh ",
      bank: "Federal Bank",
      teledata: "Transfer",
      account: "A/C:****5748",
    },
    {
      name: "Pankaj Chaudhary",
      bank: "State Bank",
      teledata: "Transfer",
      account: "A/C:****5748",
    },
    {
      name: "Pankajraj Chaudhary",
      bank: "State Bank",
      teledata: "Transfer",
      account: "A/C:****5748",
    },
    {
      name: "Rohit Sharma",
      bank: "HDFC Bank",
      teledata: "Transfer",
      account: "A/C:****5748",
    },
    {
      name: "Ankit Sharma",
      bank: "Bank of baroda Bank",
      teledata: "Transfer",
      account: "A/C:****5748",
    },
    {
      name: "Raghvendra Singh",
      bank: "Central Bank",
      teledata: "Transfer",
      account: "A/C:****5748",
    },
    {
      name: "Vimal Sahani",
      bank: "Federal Bank",
      teledata: "Transfer",
      account: "A/C:****5748",
    },
    {
      name: "Varun Yadav",
      bank: "Federal Bank",
      teledata: "Transfer",
      account: "A/C:****5748",
    },
    {
      name: "Varun Yadav",
      bank: "Federal Bank",
      teledata: "Transfer",
      account: "A/C:****5748",
    },
    {
      name: "Varun Yadav",
      bank: "Federal Bank",
      teledata: "Transfer",
      account: "A/C:****5748",
    },
    {
      name: "Varun Yadav",
      bank: "Federal Bank",
      teledata: "Transfer",
      account: "A/C:****5748",
    },
    {
      name: "Varun Yadav",
      bank: "Federal Bank",
      teledata: "Transfer",
      account: "A/C:****5748",
    },
    {
      name: "Vimal Sahani",
      bank: "Federal Bank",
      teledata: "Transfer",
      account: "A/C:****5748",
    },
    {
      name: "Varun Yadav",
      bank: "Federal Bank",
      teledata: "Transfer",
      account: "A/C:****5748",
    },
    {
      name: "Varun Yadav",
      bank: "Federal Bank",
      teledata: "Transfer",
      account: "A/C:****5748",
    },
    {
      name: "Varun Yadav",
      bank: "Federal Bank",
      teledata: "Transfer",
      account: "A/C:****5748",
    },
    {
      name: "Varun Yadav",
      bank: "Federal Bank",
      teledata: "Transfer",
      account: "A/C:****5748",
    },
    {
      name: "Varun Yadav",
      bank: "Federal Bank",
      teledata: "Transfer",
      account: "A/C:****5748",
    },
  ];